language: c

#checking out packages availability
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgtk2.0-dev autopoint libgettextpo-dev libstroke0-dev guile-2.0-dev flex bison groff texinfo python2.7-dev

script: echo hola
