# Most explicit routing to GCE Precise
sudo: required
dist: precise
group: edge

language: c

before_install: #checking out packages availability
  - sudo apt-get update
  - sudo apt-get -y install gdb

script: echo hola
